### ISSUE TITLE
Range constraint only allows ints for min and max, but Symfony says otherwise

### ISSUE THREAD

**Issue by ruben-performation** [bjd-php/parsley-bundle#16]
Hi,

Funny that nobody noticed this:

![image](https://user-images.githubusercontent.com/66825673/84489561-28f44d00-aca2-11ea-90b2-3cb02fe6c968.png)

https://symfony.com/doc/3.4/reference/constraints/Range.html#min

![image](https://user-images.githubusercontent.com/66825673/84489614-3b6e8680-aca2-11ea-8fb2-b6adfc47709f.png)

If you add min option as a float, for instance: 0.5, then you get an error, because parsley wants it to be an int.

**Comment by J-Ben87** [comment]
Thank you for the notice, I fixed it :wink:
