### ISSUE TITLE
LessThan, LessThanOrEquals, GreaterThan, GreaterThanOrEquals can be something else than just an int type

### ISSUE THREAD

**Issue by ruben-performation** [bjd-php/parsley-bundle#18]
Hi,

Parsley only allows the **type** to be **int** for the following constraints:
- LessThan
- LessThanOrEquals
- GreaterThan
- GreaterThanOrEquals

As can be seen from this code snippet of for example LessThan:
![image](https://user-images.githubusercontent.com/66825673/95874004-bb038380-0d70-11eb-815d-6f738f4ad0da.png)

But according to the Symfony documentation, it can be more than an **int**:
![image](https://user-images.githubusercontent.com/66825673/95873700-75df5180-0d70-11eb-8e8e-85943daf4ba7.png)

https://symfony.com/doc/4.4/reference/constraints/LessThan.html#value
https://symfony.com/doc/4.4/reference/constraints/LessThanOrEqual.html#value
https://symfony.com/doc/4.4/reference/constraints/GreaterThan.html#value
https://symfony.com/doc/4.4/reference/constraints/GreaterThanOrEqual.html#value

Can you at least make the allowed type **numeric**, so floats can be used as well.

Thanks in Advance,

With kind regards,
Ruben

**Comment by Matts** [comment]
I will submit PR for this tonight.
