### ISSUE TITLE
Availability for symfony forms 5.4

### ISSUE THREAD

**Issue by AntonHofmann** [bjd-php/parsley-bundle#20]
Will there be a new version of this bundle for symfony forms 5.4.x?

**Comment by J-Ben87** [comment]
Sorry for the delay, I finally published a new version of the bundle supporting PHP 7.4 to 8.1 and Symfony ^5.4 and ^6.0: https://github.com/bjd-php/parsley-bundle/releases/tag/v3.0.0

**Comment by AntonHofmann** [comment]
Thanks a lot!!
